// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Squares.Infrastructure.Persistence;

#nullable disable

namespace Squares.Infrastructure.Migrations
{
    [DbContext(typeof(SquaresDbContext))]
    [Migration("20260119132507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Squares.Domain.Entities.PointList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PointLists");
                });

            modelBuilder.Entity("Squares.Domain.Entities.PointList", b =>
                {
                    b.OwnsMany("Squares.Domain.Entities.Point", "Points", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("PointListId")
                                .HasColumnType("integer");

                            b1.Property<int>("x")
                                .HasColumnType("integer");

                            b1.Property<int>("y")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PointListId");

                            b1.ToTable("Points", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PointListId");
                        });

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
